polling_app-main/mysite/urls.py
from django.shortcuts import redirect

from django.contrib import admin
from django.urls import include, path
from . import views

def redirect_view(request):
    response = redirect('home/')
    return response

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('polls/', include('polls.urls', namespace="polls")),
    path('',redirect_view)
]

polling_app-main/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list/', views.ListView.as_view(), name='list'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polling_app-main/polls/models.py
# Create your models here.
import datetime

from django.db import models
from django.utils import timezone
import secrets



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    active = models.BooleanField(default=True)
    
    @property
    def get_vote_count(self):
        sum=0
        for choice in self.choice_set.all():
            sum += choice.votes
        return sum

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def get_result_dict(self):
        res = []
        for choice in self.choice_set.all():
            d = {}
            alert_class = ['primary', 'secondary', 'success',
                           'danger', 'dark', 'warning', 'info']

            d['alert_class'] = secrets.choice(alert_class)
            d['text'] = choice.choice_text
            d['num_votes'] = choice.get_vote_count
            if not self.get_vote_count:
                d['percentage'] = 0
            else:
                d['percentage'] = (choice.get_vote_count /
                                   self.get_vote_count)*100

            res.append(d)
        return res

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    @property
    def get_vote_count(self):
        return self.votes


    def __str__(self):
        return self.choice_text

polling_app-main/mysite/views.py
from django.shortcuts import render


def home(request):
    return render(request,'home.html')

polling_app-main/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.db.models import F

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]

class ListView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')




class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes = F('votes') + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polling_app-main/polls/templates/polls/detail.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
    <h1>Polls details page</h1>
    <hr>
    <h2 class="mt-3 mb-3">{{ question }}</h2>
    <form action="{% url 'polls:vote' question.id %}" method="POST">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <br>
        {% endfor %}
        <input type="submit" value="Vote" class="btn btn-primary mt-3">
        <a class="btn btn-warning mt-3" href="{% url 'polls:list' %}" role="button">Cancel</a>
    </form>

</div>

{% endblock content %}

polling_app-main/polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <h1 class="text-center mt-3 mb-3">Welcome to latest polls List!</h1>

            {% if latest_question_list %}
                <ul class="list-group">
                    {% for question in latest_question_list %}
                    {% if not question.active%}
                    <li class="list-group-item"><a href="{% url 'polls:results' question.id %}">{{question.question_text}}
                        <i class="fas fa-check-circle ml-2"></i>
                        </a>
                        
                    </li>
                    {% else %}
                    <li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}
                        </a>
                        
                    </li>
                    {% endif %}
                    {% endfor %}
                </ul>
            {% else %}
                <p>No polls are available.</p>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}

polling_app-main/polls/templates/polls/results.html
{% extends 'base.html' %}

{% block content %}
<div class="container">


    <div class="row">
        <div class="col-md-8 offset-sm-2">
            {% if question.active %}
            <h3 class="mt-3 mb-3 text-center">Result for: {{ question.question_text }}</h3>
            {% else %}
            <h3 class="mt-3 mb-3 text-center">"{{ question.question_text }}" Has Ended Polling !</h3>
            {% endif %}
            <h3 class="mb-2 text-center">Total: {{ question.get_vote_count }} votes</h3>
            <!-- progress bar -->
            <div class="progress mt-3 mb-2">
                {% for choice in question.get_result_dict %}
                <div class="progress-bar bg-{{ choice.alert_class }}" role="progressbar" style="width: {{ choice.percentage }}%;"
                    aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"><b>
                        {{choice.choice_text|truncatewords:2}}-{{choice.percentage|floatformat}}%</b>
                </div>
                {% endfor %}

            </div>
            <ul class="list-group">
                {% for choice in question.choice_set.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ choice.choice_text }}
                    <span class="badge badge-primary badge-pill">{{ choice.get_vote_count }}</span>
                </li>
                {% endfor %}
            </ul>
            <a class="btn btn-primary mt-3" href="{% url 'polls:list' %}" role="button">Back To Polls</a>
        </div>

    </div>


</div>
{% endblock content %}

polling_app-main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Swann Polls</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">

    {% block custom_css %}{% endblock custom_css %}

</head>

<body>
    {% include 'includes/navbar.html' %}

    {% block content %}

    {% endblock content %}


    <!-- All javascript files goes under here    -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>

</html>

polling_app-main/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block custom_css %}
<link rel="stylesheet" href="{% static 'css/home_style.css' %}">
{% endblock custom_css %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div id="home-content">
                <h1>Swann's Polling</h1>
                <h3>I am listenning to you!</h3>
                <hr>
                <a class="btn btn-light btn-lg" href="{% url 'polls:list' %}" role="button">Start voting !</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

polling_app-main/templates/includes/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light">
    <a class="navbar-brand" href=""><i class="fas fa-person-booth"></i></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
        aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'polls:list' %}">Polls</a>
            </li>
        </ul>
        <div class="navbar-nav ml-auto">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </div>
    </div>
</nav>